export const SET_SAVED = "SET_SAVED";
export const SET_RAW_LIST = "SET_RAW_LIST";
export const SET_DICTIONARY_CITY = "SET_DICTIONARY_CITY";
export const SET_FILTERS = "SET_FILTERS";
export const SET_PAGINATION = "SET_PAGINATION";
export const SET_CURRENT_SEARCH_ID = "SET_CURRENT_SEARCH_ID";
